"""initial migrations

Revision ID: 28bebd22ed51
Revises: 71aac656dcee
Create Date: 2019-06-06 18:07:58.389809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28bebd22ed51'
down_revision = '71aac656dcee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chats_username', table_name='chats')
    op.drop_constraint('chats_user_id_fkey', 'chats', type_='foreignkey')
    op.drop_constraint('chats_debate_id_fkey', 'chats', type_='foreignkey')
    op.drop_column('chats', 'username')
    op.drop_column('chats', 'chat_id')
    op.drop_column('chats', 'user_id')
    op.drop_column('chats', 'debate_id')
    op.drop_column('chats', 'posted')
    op.drop_column('chats', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('chats', sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('chats', sa.Column('debate_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chats', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chats', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chats', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key('chats_debate_id_fkey', 'chats', 'debates', ['debate_id'], ['id'])
    op.create_foreign_key('chats_user_id_fkey', 'chats', 'users', ['user_id'], ['id'])
    op.create_index('ix_chats_username', 'chats', ['username'], unique=False)
    # ### end Alembic commands ###
