"""...

Revision ID: 2ed28573fd02
Revises: 28bebd22ed51
Create Date: 2019-06-06 18:14:10.300440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed28573fd02'
down_revision = '28bebd22ed51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('debates_user_id_fkey', 'debates', type_='foreignkey')
    op.drop_column('debates', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debates', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('debates_user_id_fkey', 'debates', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
