"""...

Revision ID: 9b92c20b5ff8
Revises: 2ed28573fd02
Create Date: 2019-06-06 18:16:20.001101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b92c20b5ff8'
down_revision = '2ed28573fd02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debates', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'debates', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'debates', type_='foreignkey')
    op.drop_column('debates', 'user_id')
    # ### end Alembic commands ###
