"""empty message

Revision ID: be06c76dadca
Revises: 171ec4ace26f
Create Date: 2019-06-06 20:21:51.905378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be06c76dadca'
down_revision = '171ec4ace26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('chat', sa.String(), nullable=True))
    op.drop_column('chats', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('chats', 'chat')
    # ### end Alembic commands ###
